apiVersion: apps/v1
kind: Deployment
metadata:
  name: castle-frontend
  labels:
    app: castle-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: castle-frontend
  template:
    metadata:
      labels:
        app: castle-frontend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      containers:
        - name: castle-frontend
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: PORT
              value: "{{ .Values.app.port }}"
          livenessProbe: 
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: 
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
