import type { TranslationLocale } from "../localization/TranslationLocale";
import type { User2faData } from "./User2faData";
import type { UserAffiliateData } from "./UserAffiliateData";
import type { UserBanData } from "./UserBanData";
import type { UserChestKeys } from "./UserChestKeys";
import type { UserKycData } from "./UserKycData";
import type { UserMetaData } from "./UserMetaData";
import type { UserMuteData } from "./UserMuteData";
import type { UserReferer } from "./UserReferer";
import type { UserReferral } from "./UserReferral";
import type { UserRole } from "./UserRole";
import type { UserSettings } from "./UserSettings";
import type { UserStats } from "./UserStats";
import type { UserSuspensionData } from "./UserSuspensionData";
import type { UserTag } from "./UserTag";

export interface UserDocument {
  _id: string;
  registerDate: Date;
  referer: UserReferer;
  referral?: UserReferral;
  locale: TranslationLocale;
  username: string;
  email: string;
  emailConfirmed: boolean;
  role: UserRole;
  tags: UserTag[];
  avatarIndex: number;
  avatarId?: string;
  tokenBalance: number;
  vaultBalance?: number;
  gemBalance: number;
  holidayBalance?: number;
  xp: number;
  stats: UserStats;
  chestKeys: UserChestKeys;
  settings: UserSettings;
  passwordHash?: string;
  passwordSet: boolean;
  steamId?: string;
  googleId?: string;
  discordId?: string;
  twitchId?: string;
  walletAddress?: string;
  affiliate: UserAffiliateData;
  tfa: User2faData;
  kyc: UserKycData;
  mute: UserMuteData;
  suspension: UserSuspensionData;
  ban: UserBanData;
  blockedUsers: string[];
  meta: UserMetaData;
}
