replicaCount: 1

image:
  app:
    repository: "183631306381.dkr.ecr.us-east-1.amazonaws.com/pidwin/castle-admin-backend"
    pullPolicy: Always
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Use a single service block for consistency.
service:
  type: ClusterIP
  port: 3000
  tls: []

ingress:
  enabled: false

secrets:
  app: "shared-admin-backend"
  
app:
  port: 3000

resources: {}

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: {}
affinity: {}

namespace: shared-admin-backend

# Explicit labels for consistency
labels:
  app: castle-admin-backend
