apiVersion: apps/v1
kind: Deployment
metadata:
  name: castle-backend
  labels:
    app: castle-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: castle-backend
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: castle-backend
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: castle-backend
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.app }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: PORT
              value: "{{ .Values.app.port }}"
            - name: NODE_ENV
              value: {{ .Values.environment }}
            - name: APP_ENV
              value: {{ .Values.environment }}
            - name: env
              value: {{ .Values.environment }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
