apiVersion: v1
kind: ConfigMap
metadata:
  name: castle-backend-envoy-config
  namespace: {{ .Values.namespace }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_https
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: {{ .Values.envoy.port }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              stat_prefix: ingress_https
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                - certificate_chain:
                    filename: /etc/certs/tls.crt
                  private_key:
                    filename: /etc/certs/tls.key
      clusters:
      - name: backend
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: backend # Important: Add this line
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: {{ .Values.app.port }}