apiVersion: v1
kind: ConfigMap
metadata:
  name: castle-backend-envoy-config
  namespace: shared-backend
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_https
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.port | default 8443 }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: backend
              http_filters:
              - name: envoy.filters.http.router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                - certificate_chain: { "filename": "/etc/certs/tls.crt" }
                  private_key: { "filename": "/etc/certs/tls.key" }
      clusters:
      - name: backend
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: backend
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: {{ .Values.app.port | default 3000 }}
