apiVersion: v1
kind: Service
metadata:
  name: castle-backend
  labels:
    app: castle-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443  
      protocol: TCP
  selector:
    app: castle-backend
