services:
  mongo:
    image: mongo:latest
    container_name: mongo-pidwin-local
    hostname: mongo-pidwin
    ports:
      - "27778:27017"
    command: ["--replSet", "dbrs"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis-pidwin-local
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo-init:
    image: mongo:latest
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 5 &&
       mongosh --host mongo-pidwin --quiet --eval 'rs.initiate()'"
