import { Intimal } from "#core/services/intimal";
import { CryptoInfo } from "#core/types/cryptos/CryptoInfo";

export const infos: CryptoInfo[] = [
  {
    kind: "BTC",
    symbol: "BTC",
    name: "Bitcoin",
    assetId: "BTC",
    walletType: "utxo",
    decimals: 8,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(50),
    canDeposit: true,
    canWithdraw: true,
    explorerUrl: "https://blockchair.com/bitcoin/transaction/",
  },
  {
    kind: "LTC",
    symbol: "LTC",
    name: "Litecoin",
    assetId: "LTC",
    walletType: "utxo",
    decimals: 8,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(20),
    canDeposit: true,
    canWithdraw: true,
    explorerUrl: "https://blockchair.com/litecoin/transaction/",
  },
  {
    kind: "ETH",
    symbol: "ETH",
    name: "Ethereum",
    assetId: "ETH",
    walletType: "account",
    decimals: 18,
    confirms: 2,
    minWithdrawTokens: Intimal.fromDecimal(20),
    canDeposit: true,
    canWithdraw: true,
    explorerUrl: "https://etherscan.io/tx/",
  },
  {
    kind: "USDC_ERC-20",
    symbol: "USDC",
    network: "ERC-20",
    networkCoin: "ETH",
    name: "USD Coin",
    assetId: "USDC",
    walletType: "account",
    decimals: 6,
    confirms: 2,
    minWithdrawTokens: Intimal.fromDecimal(20),
    isToken: true,
    canDeposit: true,
    canWithdraw: true,
    explorerUrl: "https://etherscan.io/tx/",
  },
  {
    kind: "USDT_ERC-20",
    symbol: "USDT",
    network: "ERC-20",
    networkCoin: "ETH",
    name: "Tether USD",
    assetId: "USDT_ERC20",
    walletType: "account",
    decimals: 6,
    confirms: 2,
    minWithdrawTokens: Intimal.fromDecimal(20),
    isToken: true,
    canDeposit: true,
    canWithdraw: true,
    explorerUrl: "https://etherscan.io/tx/",
  },
  {
    kind: "USDT_TRC-20",
    symbol: "USDT",
    network: "TRC-20",
    networkCoin: "TRX",
    name: "Tether USD",
    assetId: "TRX_USDT_S2UZ",
    walletType: "account",
    decimals: 6,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(20),
    isToken: true,
    canDeposit: true,
    canWithdraw: true,
    explorerUrl: "https://tronscan.org/#/transaction/",
  },
  {
    kind: "DOGE",
    symbol: "DOGE",
    name: "Dogecoin",
    assetId: "DOGE",
    walletType: "utxo",
    decimals: 8,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(20),
    canDeposit: true,
    canWithdraw: false,
    explorerUrl: "https://blockchair.com/dogecoin/transaction/",
  },
  {
    kind: "SOL",
    symbol: "SOL",
    name: "Solana",
    assetId: "SOL",
    walletType: "account",
    decimals: 9,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(20),
    canDeposit: true,
    canWithdraw: false,
    explorerUrl: "https://explorer.solana.com/tx/",
  },
  {
    kind: "ADA",
    symbol: "ADA",
    name: "Cardano",
    assetId: "ADA",
    walletType: "utxo",
    decimals: 6,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(20),
    canDeposit: true,
    canWithdraw: false,
    explorerUrl: "https://cardanoscan.io/transaction/",
  },
  {
    kind: "TRX",
    symbol: "TRX",
    name: "TRON",
    assetId: "TRX",
    walletType: "account",
    decimals: 18,
    confirms: 1,
    minWithdrawTokens: Intimal.fromDecimal(20),
    canDeposit: true,
    canWithdraw: false,
    explorerUrl: "https://tronscan.org/#/transaction/",
  },
];
