import type { AdminLogDocument } from "../admin/AdminLogDocument";
import type { AdventTicketDocument } from "../rewards/AdventTicketDocument";
import type { AffiliateKeyDocument } from "../affiliates/AffiliateKeyDocument";
import type { AffiliateReferralDocument } from "../affiliates/AffiliateReferralDocument";
import type { AffiliateReportDocument } from "../affiliates/AffiliateReport";
import type { AffiliateReloadDocument } from "../affiliates/AffiliateReloadDocument";
import type { CaseBattleDocument } from "../case-battles/CaseBattleDocument";
import type { ChatMessageDocument } from "../chat/ChatMessageDocument";
import type { ChatRainDocument } from "../chat/ChatRainDocument";
import type { ChatRainTicketDocument } from "../chat/ChatRainTicketDocument";
import type { ChestDocument } from "../chests/ChestDocument";
import type { ChestDropDocument } from "../chests/ChestDropDocument";
import type { ChestGameDocument } from "../chests/ChestGameDocument";
import type { ChestReportDocument } from "../chests/ChestReport";
import type { CryptoQuoteDocument } from "../cryptos/CryptoQuoteDocument";
import type { CryptoRateDocument } from "../cryptos/CryptoRateDocument";
import type { CryptoSweepDocument } from "../cryptos/CryptoSweepDocument";
import type { CryptoWalletDocument } from "../cryptos/CryptoWalletDocument";
import type { DiceTicketDocument } from "../dice/DiceTicketDocument";
import type { DoubleRoundDocument } from "../double/DoubleRoundDocument";
import type { DoubleTicketDocument } from "../double/DoubleTicketDocument";
import type { GiftBatchDocument } from "../economy/GiftBatchDocument";
import type { GiftCardDocument } from "../economy/GiftCardDocument";
import type { EmailInfoDocument } from "../http/EmailInfoDocument";
import type { HolidayEventDocument } from "../rewards/HolidayEventDocument";
import type { IpInfoDocument } from "../http/IpInfoDocument";
import type { IncrementalDocument } from "../ids/IncrementalDocument";
import type { ItemDocument } from "../items/ItemDocument";
import type { LimboTicketDocument } from "../limbo/LimboTicketDocument";
import type { MarketInventoryDocument } from "../market/MarketInventoryDocument";
import type { MarketItemDocument } from "../market/MarketItemDocument";
import type { NotificationDocument } from "../notifications/NotificationDocument";
import type { PromotionCodeDocument } from "../economy/PromotionCodeDocument";
import type { PromotionTicketDocument } from "../economy/PromotionTicketDocument";
import type { RaceDocument } from "../rewards/RaceDocument";
import type { RaffleDocument } from "../rewards/RaffleDocument";
import type { RaffleTicketDocument } from "../rewards/RaffleTicketDocument";
import type { RewardBoostEventDocument } from "../rewards/RewardBoostEventDocument";
import type { RewardBoostTicketDocument } from "../rewards/RewardBoostTicketDocument";
import type { RewardClaimDocument } from "../rewards/RewardClaimDocument";
import type { RewardProductDocument } from "../rewards/RewardProductDocument";
import type { SiteSettingDocument } from "../site/SiteSettingDocument";
import type { SwappedTicketDocument } from "../economy/SwappedTicketDocument";
import type { SwappedWalletDocument } from "../economy/SwappedWalletDocument";
import type { SiteActivityDocument } from "../site/SiteActivityDocument";
import type { SiteBetDocument } from "../site/SiteBetDocument";
import type { SiteMetaDocument } from "../site/SiteMetaDocument";
import type { SiteStatsDocument } from "../site/SiteStatsDocument";
import type { SystemLogDocument } from "../system/SystemLogDocument";
import type { TokenDocument } from "../security/TokenDocument";
import type { TransactionReportDocument } from "../transactions/TransactionReport";
import type { TransactionDocument } from "../transactions/TransactionDocument";
import type { UserCampaigns } from "../users/UserCampaigns";
import type { UserDocument } from "../users/UserDocument";
import type { UserActionDocument } from "../users/UserActionDocument";
import type { UserBetSessionDocument } from "../users/UserBetSessionDocument";
import type { UserHoldDocument } from "../users/UserHold";
import type { UserReportDocument } from "../users/UserReport";
import type { UserSeedPairDocument } from "../users/UserSeedPairDocument";
import type { UserSessionDocument } from "../users/UserSessionDocument";
import { SiteGameDisplayDocument } from "../site/SiteGameDisplayDocument";
import { SiteJackPotDocument } from "../site/SiteJackpotDocument";
import { MinesGameDocument } from "../mines/MinesGameDocument";
import { MinesEventDocument } from "../mines/MinesEventDocument";
import { CrashRoundDocument } from "../crash/CrashRoundDocument";
import { CrashTicketDocument } from "../crash/CrashTicketDocument";
import { UserLatencyDocument } from "../users/UserLatencyDocument";

export interface DatabaseCollections {
  ["admin-log"]: AdminLogDocument;
  ["admin-sessions"]: UserSessionDocument;
  ["advent-tickets"]: AdventTicketDocument;
  ["affiliate-keys"]: AffiliateKeyDocument;
  ["affiliate-referrals"]: AffiliateReferralDocument;
  ["affiliate-reports"]: AffiliateReportDocument;
  ["affiliate-reloads"]: AffiliateReloadDocument;
  ["case-battles"]: CaseBattleDocument;
  ["chat-messages"]: ChatMessageDocument;
  ["chat-rains"]: ChatRainDocument;
  ["chat-rain-tickets"]: ChatRainTicketDocument;
  ["chest-drops"]: ChestDropDocument;
  ["chest-games"]: ChestGameDocument;
  ["chest-reports"]: ChestReportDocument;
  ["chests"]: ChestDocument;
  ["crash-records"]: CrashRecordDocument;
  ["crypto-quotes"]: CryptoQuoteDocument;
  ["crypto-rates"]: CryptoRateDocument;
  ["crypto-sweeps"]: CryptoSweepDocument;
  ["crypto-wallets"]: CryptoWalletDocument;
  ["dice-tickets"]: DiceTicketDocument;
  ["double-rounds"]: DoubleRoundDocument;
  ["double-tickets"]: DoubleTicketDocument;
  ["email-info"]: EmailInfoDocument;
  ["gift-batches"]: GiftBatchDocument;
  ["gift-cards"]: GiftCardDocument;
  ["holiday-events"]: HolidayEventDocument;
  ["incremental-ids"]: IncrementalDocument;
  ["ip-info"]: IpInfoDocument;
  ["items"]: ItemDocument;
  ["limbo-tickets"]: LimboTicketDocument;
  ["market-inventories"]: MarketInventoryDocument;
  ["market-items"]: MarketItemDocument;
  ["mines-events"]: MinesEventDocument;
  ["mines-games"]: MinesGameDocument;
  ["notifications"]: NotificationDocument;
  ["promotion-codes"]: PromotionCodeDocument;
  ["promotion-tickets"]: PromotionTicketDocument;
  ["races"]: RaceDocument;
  ["raffles"]: RaffleDocument;
  ["raffle-tickets"]: RaffleTicketDocument;
  ["reward-boost-events"]: RewardBoostEventDocument;
  ["reward-boost-tickets"]: RewardBoostTicketDocument;
  ["reward-claims"]: RewardClaimDocument;
  ["reward-products"]: RewardProductDocument;
  ["swapped-tickets"]: SwappedTicketDocument;
  ["swapped-wallets"]: SwappedWalletDocument;
  ["site-activity"]: SiteActivityDocument;
  ["site-bets"]: SiteBetDocument;
  ["site-games"]: SiteGameDisplayDocument;
  ["site-jackpot"]: SiteJackPotDocument;
  ["site-meta"]: SiteMetaDocument;
  ["site-settings"]: SiteSettingDocument;
  ["site-stats"]: SiteStatsDocument;
  ["system-log"]: SystemLogDocument;
  ["tokens"]: TokenDocument;
  ["transactions"]: TransactionDocument;
  ["transaction-reports"]: TransactionReportDocument;
  ["users"]: UserDocument;
  ["user-actions"]: UserActionDocument;
  ["user-bet-sessions"]: UserBetSessionDocument;
  ["user-campaigns"]: UserCampaigns;
  ["user-holds"]: UserHoldDocument;
  ["user-reports"]: UserReportDocument;
  ["user-seed-pairs"]: UserSeedPairDocument;
  ["user-sessions"]: UserSessionDocument;
  ["user-latency"]: UserLatencyDocument;
  ["crash-rounds"]: CrashRoundDocument;
  ["crash-tickets"]: CrashTicketDocument;
}
