import { TransactionKind } from "#core/types/transactions/TransactionKind";

const kindMap: Record<TransactionKind, boolean> = {
  "admin-token-credit": true,
  "admin-token-debit": true,
  "affiliate-commission-claim": true,
  "affiliate-reload-claim": true,
  "case-battle-join": true,
  "case-battle-won": true,
  "case-item-won": true,
  "case-spin": true,
  "deposit-crypto": true,
  "deposit-gift-card": true,
  "deposit-skin": true,
  "deposit-swapped": true,
  "dice-won": true,
  "dice-bet": true,
  "double-bet": true,
  "double-jackpot-won": true,
  "double-won": true,
  "limbo-bet": true,
  "limbo-won": true,
  "mines-bet": true,
  "mines-won": true,
  "promotion-card-redeem": true,
  "promotion-code-redeem": true,
  "rain-payout": true,
  "rain-tip": true,
  "reward-advent-item": true,
  "reward-boost": true,
  "reward-claim": true,
  "reward-gem-case-item": true,
  "reward-holiday-case-item": true,
  "reward-level-case-item": true,
  "reward-token-pack": true,
  "tip-receive": true,
  "tip-send": true,
  "withdraw-crypto": true,
  "withdraw-skin": true,
  "vault-deposit": true,
  "vault-withdraw": true,
};

export const kinds = Object.keys(kindMap) as TransactionKind[];
