apiVersion: v1
kind: Service
metadata:
  name: {{ include "castle-affiliate-api.fullname" . | default "castle-affiliate-api" }}
  labels:
    app: castle-affiliate-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: castle-affiliate-api
