import { TransactionCategory } from "#core/types/transactions/TransactionCategory";
import { TransactionKind } from "#core/types/transactions/TransactionKind";

export function getCategory(kind: TransactionKind) {
  return map[kind];
}

const map: Record<TransactionKind, TransactionCategory> = {
  "admin-token-credit": "other",
  "admin-token-debit": "other",
  "affiliate-campaign-commission-claim": "referrals",
  "affiliate-commission-claim": "referrals",
  "affiliate-reload-claim": "referrals",
  "duel-bet": "duel",
  "duel-won": "duel",
  "crash-bet": "crash",
  "crash-won": "crash",
  "case-battle-join": "case-battles",
  "case-battle-won": "case-battles",
  "case-item-won": "cases",
  "case-spin": "cases",
  "deposit-crypto": "deposits",
  "deposit-gift-card": "deposits",
  "deposit-skin": "deposits",
  "deposit-swapped": "deposits",
  "dice-bet": "dice",
  "dice-won": "dice",
  "double-bet": "double",
  "double-jackpot-won": "double",
  "double-won": "double",
  "limbo-bet": "limbo",
  "limbo-won": "limbo",
  "mines-bet": "mines",
  "mines-won": "mines",
  "blackjack-bet": "blackjack",
  "blackjack-sidebet-bet": "blackjack",
  "blackjack-split": "blackjack",
  "blackjack-double": "blackjack",
  "blackjack-won": "blackjack",
  "blackjack-sidebet-won": "blackjack",
  "promotion-card-redeem": "promotion",
  "promotion-code-redeem": "promotion",
  "rain-payout": "rain",
  "rain-tip": "rain",
  "reward-advent-item": "rewards",
  "reward-boost": "rewards",
  "reward-claim": "rewards",
  "reward-faucet": "rewards",
  "reward-daily-case-item": "rewards",
  "reward-gem-case-item": "rewards",
  "reward-holiday-case-item": "rewards",
  "reward-level-case-item": "rewards",
  "reward-token-pack": "rewards",
  "tip-receive": "tips",
  "tip-send": "tips",
  "withdraw-crypto": "withdrawals",
  "withdraw-skin": "withdrawals",
  "vault-deposit": "vault",
  "vault-withdraw": "vault",
};
