/* eslint-disable no-useless-computed-key */
import { DatabaseCollections } from "@core/types/database/DatabaseCollections";
import config from "#server/config";

const names = [config.env, "messaging"] as const;

export type dbNames = (typeof names)[number];

export const dbCollectionsMapping: Readonly<Record<keyof DatabaseCollections, dbNames>> = {
  ["admin-log"]: config.env,
  ["admin-sessions"]: config.env,
  ["advent-tickets"]: config.env,
  ["affiliate-keys"]: config.env,
  ["affiliate-referrals"]: config.env,
  ["affiliate-reports"]: config.env,
  ["affiliate-reloads"]: config.env,
  ["case-battles"]: config.env,
  ["chat-messages"]: config.env,
  ["chat-rains"]: config.env,
  ["chat-rain-tickets"]: config.env,
  ["chest-drops"]: config.env,
  ["chest-games"]: config.env,
  ["chest-reports"]: config.env,
  ["chests"]: config.env,
  ["crypto-quotes"]: config.env,
  ["crypto-rates"]: config.env,
  ["crypto-sweeps"]: config.env,
  ["crypto-wallets"]: config.env,
  ["dice-tickets"]: config.env,
  ["double-rounds"]: config.env,
  ["double-tickets"]: config.env,
  ["email-info"]: config.env,
  ["gift-batches"]: config.env,
  ["gift-cards"]: config.env,
  ["holiday-events"]: config.env,
  ["incremental-ids"]: config.env,
  ["ip-info"]: config.env,
  ["items"]: config.env,
  ["limbo-tickets"]: config.env,
  ["market-inventories"]: config.env,
  ["market-items"]: config.env,
  ["mines-events"]: config.env,
  ["mines-games"]: config.env,
  ["notifications"]: config.env,
  ["promotion-codes"]: config.env,
  ["promotion-tickets"]: config.env,
  ["races"]: config.env,
  ["raffles"]: config.env,
  ["raffle-tickets"]: config.env,
  ["reward-boost-events"]: config.env,
  ["reward-boost-tickets"]: config.env,
  ["reward-claims"]: config.env,
  ["reward-products"]: config.env,
  ["swapped-tickets"]: config.env,
  ["swapped-wallets"]: config.env,
  ["site-activity"]: config.env,
  ["site-bets"]: config.env,
  ["site-games"]: config.env,
  ["site-jackpot"]: config.env,
  ["site-meta"]: config.env,
  ["site-settings"]: config.env,
  ["site-stats"]: config.env,
  ["system-log"]: config.env,
  ["tokens"]: config.env,
  ["transactions"]: config.env,
  ["transaction-reports"]: config.env,
  ["users"]: config.env,
  ["user-actions"]: config.env,
  ["user-bet-sessions"]: config.env,
  ["user-holds"]: config.env,
  ["user-reports"]: config.env,
  ["user-seed-pairs"]: config.env,
  ["user-sessions"]: config.env,
};
