replicaCount: 1

environment: "devcloud"

image:
  app:
    repository: "183631306381.dkr.ecr.us-east-1.amazonaws.com/pidwin/castle-admin-frontend"
    pullPolicy: Always
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  # Option 1: Use auto-detection for ConfigMaps/Secrets used by this deployment
  reloader.stakater.com/auto: "true"

podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

secrets:
  app: "castle-admin-frontend"
  
app:
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []   # <-- Changed to an empty list instead of an object.
affinity: {}

namespace: shared-admin-frontend

# Explicit label used by both Deployment and Service
labels:
  app: castle-admin-frontend
