replicaCount: 1

image:
  app:
    repository: "183631306381.dkr.ecr.us-east-1.amazonaws.com/pidwin/castle-admin-frontend"
    pullPolicy: Always
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

secrets:
  app: "castle-admin-frontend"
  
app:
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: {}
affinity: {}

namespace: shared-admin-frontend

# Explicit label used by both Deployment and Service
labels:
  app: castle-admin-frontend
