import { AdminLogKind } from "#core/types/admin/AdminLogKind";

const kindMap: Record<AdminLogKind, boolean> = {
  "affiliate-base-tier": true,
  "affiliate-key-create": true,
  "affiliate-key-disable": true,
  "affiliate-reload-create": true,
  "affiliate-reload-edit": true,
  "chat-delete": true,
  "chest-create": true,
  "chest-disable": true,
  "chest-enable": true,
  "chest-update": true,
  "crypto-deposit-confirm": true,
  "crypto-withdraw-approve": true,
  "crypto-withdraw-cancel": true,
  "gift-batch-create": true,
  "holiday-create": true,
  "promotion-code-cancel": true,
  "promotion-code-create": true,
  "race-create": true,
  "raffle-create": true,
  "reward-boost-event-create": true,
  "reward-boost-event-edit": true,
  "reward-product-create": true,
  "reward-product-edit": true,
  "setting-edit": true,
  "skin-withdraw-approve": true,
  "skin-withdraw-cancel": true,
  "token-credit": true,
  "token-debit": true,
  "user-authenticator-disable": true,
  "user-ban": true,
  "user-email": true,
  "user-mute": true,
  "user-name": true,
  "user-referral": true,
  "user-role": true,
  "user-suspension": true,
  "user-tags": true,
  "user-tip-limit": true,
};

export const logKinds = Object.keys(kindMap) as AdminLogKind[];
