replicaCount: 1

image:
  app:
    repository: "183631306381.dkr.ecr.us-east-1.amazonaws.com/pidwin/castle-backend"
    pullPolicy: Always
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false

secrets:
  app: "shared-backend"

service:
  type: ClusterIP
  port: 3000
  tls: []

app:
  port: 3000

resources: {}

# Default liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

namespace: shared-backend

# Explicit labels to ensure consistency across resources
labels:
  app: castle-backend


envoy:
  enabled: true
  image: "envoyproxy/envoy:v1.29.0" # Use a stable Envoy version
  port: 8443 # Port Envoy will listen on for HTTPS
  adminPort: 9901 # Envoy admin interface port (for debugging)
  certificateSecret: "shared-backend-tls" # Name of the secret in the current namespace

volumes:
  # - name: envoy-config
  #   configMap:
  #     name: castle-backend-envoy-config # Use the chart's name for the ConfigMap
  - name: tls-certs
    secret:
      secretName: "shared-backend-tls"

