replicaCount: 1

image:
  app:
    repository: "183631306381.dkr.ecr.us-east-1.amazonaws.com/pidwin/castle-frontend"
    pullPolicy: Always
    tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  tls: []

ingress:
  enabled: false

secrets:
  app: "castle-frontend"

app:
  port: 80

resources: {}

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

namespace: shared-admin-backend

# Added explicit label for our app
labels:
  app: castle-frontend
