replicaCount: 1

environment: "devcloud"

image:
  app:
    repository: "183631306381.dkr.ecr.us-east-1.amazonaws.com/pidwin/castle-frontend"
    pullPolicy: Always
    tag: "latest"

# New section for runtime configuration values
runtimeConfig:
  appEnvName: "devcloud"
  siteUrl: "https://dev.brickrax.com"
  siteApi: "https://api.dev.brickrax.com"
  adminUrl: "https://admin.dev.brickrax.com"
  adminApi: "https://aapi.dev.brickrax.com"
  staticUrl: "https://font.brickrax.com" # As defined in coreConfig

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  # Option 1: Use auto-detection for ConfigMaps/Secrets used by this deployment
  reloader.stakater.com/auto: "true"
  
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  tls: []

ingress:
  enabled: false

secrets:
  app: "castle-frontend"

app:
  port: 80

resources: {}

# Default liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

namespace: shared-admin-backend

# Explicit labels to ensure consistency
labels:
  app: castle-frontend
