name: Castle Backend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - "packages/shared-backend/**"
      - ".github/workflows/deploy_shared_be.yml"

jobs:
  build-and-push-shared-backend:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.PIDWIN_READ_ONLY_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: set-image-tag
        run: |
          # Generate an immutable version tag using a timestamp
          IMAGE_TAG="v1.0.$(date +%s)"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Generated IMAGE_TAG: $IMAGE_TAG"

      - name: Build and tag Docker image
        run: |
          IMAGE_TAG="${{ steps.set-image-tag.outputs.image_tag }}"
          docker build -t pidwin/castle-backend -f ./packages/shared-backend/Dockerfile .
          # Tag the image with the generated version tag
          docker tag pidwin/castle-backend:latest ${{ steps.login-ecr.outputs.registry }}/pidwin/castle-backend:$IMAGE_TAG
          # Optionally, tag it as 'latest' for fallback purposes
          docker tag pidwin/castle-backend:latest ${{ steps.login-ecr.outputs.registry }}/pidwin/castle-backend:latest

      - name: Push Docker images to ECR
        run: |
          IMAGE_TAG="${{ steps.set-image-tag.outputs.image_tag }}"
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker push $REGISTRY/pidwin/castle-backend:$IMAGE_TAG
          docker push $REGISTRY/pidwin/castle-backend:latest

      - name: Output ECR Image URL
        run: |
          echo "Image pushed to ECR with tags:"
          echo "Version tag: ${{ steps.login-ecr.outputs.registry }}/pidwin/castle-backend:${{ steps.set-image-tag.outputs.image_tag }}"
          echo "Latest tag: ${{ steps.login-ecr.outputs.registry }}/pidwin/castle-backend:latest"

  update-argocd-dev:
    needs: build-and-push-shared-backend
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: Update ArgoCD Application for DEV
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure --grpc-web
          argocd app set castle-be --helm-set image.app.tag=${{ needs.build-and-push-shared-backend.outputs.image_tag }}
          argocd app sync castle-be --async

  # update-argocd-stage:
  #   needs: update-argocd-dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update ArgoCD Application for STAGE
  #       env:
  #         IMAGE_TAG: ${{ needs.build-and-push-shared-backend.outputs.image_tag }}
  #         ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
  #         ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
  #         ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
  #       run: |
  #         argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
  #         argocd app set castle-be-stage --helm-set image.app.tag=$IMAGE_TAG
  #         argocd app sync castle-be-stage

  # wait-for-prod-approval:
  #   needs: update-argocd-stage
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Wait for Production Approval
  #       uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: csherida,civilizador
  #         minimum-approvals: 1
  #         issue-title: "Deploying to production"
  #         issue-body: "Please approve or deny the deployment of this version"
  #         exclude-workflow-initiator-as-approver: false
  #         fail-on-denial: true

  # update-argocd-prod:
  #   needs: wait-for-prod-approval
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update ArgoCD Application for PROD
  #       env:
  #         IMAGE_TAG: ${{ needs.build-and-push-shared-backend.outputs.image_tag }}
  #         ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
  #         ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
  #         ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
  #       run: |
  #         argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
  #         argocd app set castle-backend-prod --helm-set image.app.tag=$IMAGE_TAG
  #         argocd app sync castle-backend-prod
