name: PR Checks

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'helm/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.PIDWIN_READ_ONLY_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run eslint
        continue-on-error: true

# ENABLE WHEN JEST TEST ARE READY
      # - name: Run Jest Tests
      #   run: npm test

      - name: Check Build React app
        run: npm run init
